type Address implements Node {
  address: String
  id: ID!
  lat: Float
  location: Location!
  long: Float
  name: String
  postalCode: String
}

"""
A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar Date

scalar DurationType

"""
The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSONObject

"""Links contains Website URL, Twitter Username and list of Links"""
scalar Links

type Location implements Node {
  addresses(after: ID, before: ID, first: Int, last: Int): LocationAddressesConnection!
  city: String!
  country: String!
  id: ID!
  profiles(after: ID, before: ID, first: Int, last: Int, oldestFirst: Boolean): LocationProfilesConnection!
  state: String
  trips(after: ID, before: ID, first: Int, last: Int, oldestFirst: Boolean): LocationTripsConnection!
}

type LocationAddressesConnection {
  edges: [LocationAddressesConnectionEdge]!
  pageInfo: PageInfo!
}

type LocationAddressesConnectionEdge {
  cursor: String!
  node: Address!
}

input LocationInput {
  city: String!
  country: String!
  state: String!
}

type LocationProfilesConnection {
  edges: [LocationProfilesConnectionEdge]!
  pageInfo: PageInfo!
}

type LocationProfilesConnectionEdge {
  cursor: String!
  node: Profile!
}

type LocationTripsConnection {
  edges: [LocationTripsConnectionEdge]!
  pageInfo: PageInfo!
}

type LocationTripsConnectionEdge {
  cursor: String!
  node: Trip!
}

type Mutation {
  createAddress(address: String, lat: Float, locationId: ID!, long: Float, name: String!, postalCode: String): Address!
  createLocation(city: String!, country: String!, profileId: ID, state: String!, tripId: ID): Location!
  createTrip(description: String, location: LocationInput, locationId: String, title: String!): Trip!
  createUser(email: String!, name: String!, tagline: String): User!
  deleteAddress(id: ID!): Address!
  deleteLocation(id: ID!): Location!
  deleteTrip(id: ID!): Trip!
  deleteUser(email: String!, name: String!): User!
  editAddress(address: String, id: ID!, lat: Float, long: Float, name: String!, postalCode: String): Address!
  editLocation(city: String, country: String, id: ID!, state: String): Location!
  editTrip(description: String, id: ID!, title: String!): Trip!
}

interface Node {
  id: ID!
}

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
}

type Profile {
  description: String
  email: String
  id: String!
  location: Location!
  user: User!
}

type Query {
  Address: [Address!]!
  Location: [Location!]!
  Profile: [Profile!]!
  Trip: [Trip!]!
  Users: [User!]!
  node(id: ID!): Node
  nodes(ids: [ID!]!): [Node]!
}

type Trip {
  description: String
  id: String!
  location: Location!
  title: String!
  users: [User!]
}

type TripsOnUsers {
  assignedAt: Date!
  assignedBy: String!
  id: ID!
  trip: Trip!
  user: User!
}

type User {
  description: String
  email: String!
  id: String!
  name: String
  profile: Profile
  tagline: String
  tripOnCity(city: String!): String
  trips(after: ID, before: ID, first: Int, last: Int): UserTripsConnection!
}

type UserTripsConnection {
  edges: [UserTripsConnectionEdge]!
  pageInfo: PageInfo!
}

type UserTripsConnectionEdge {
  cursor: String!
  node: TripsOnUsers!
}