/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
type BodyMapInputInputType = {
    details: string;
    label: string;
};
export type CreateReportMutation = {
    createReport: {
        id: string;
        name: string;
        date: any;
        bodymaps: ({
            label: string;
            details: string;
        })[];
        user: {
            id: string;
            name: string | null;
        };
    };
};
export type CreateReportMutationVariables = {
    name: string;
    date: any;
    email: string;
    bodymaps: BodyMapInputInputType[];
};
