/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type FeedQuery = {
    feed: ({
        id: string;
        name: string;
        date: any;
        createdAt: any;
    })[];
};
export type FeedQueryVariables = {};
