/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type HelloUser = {
    Users: ({
        name: string | null;
    })[];
};
export type HelloUserVariables = {};
