/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type CreateBodyMapMutation = {
    createBodyMap: {
        id: string;
        label: string;
        details: string;
        report: {
            id: string;
            name: string;
        };
    };
};
export type CreateBodyMapMutationVariables = {
    reportId: string;
    label: string;
    details: string;
};
