/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type DeleteBodyMapMutation = {
    deleteBodyMap: {
        id: string;
        label: string;
        details: string;
    };
};
export type DeleteBodyMapMutationVariables = {
    id: string;
};
