/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type EditReportMutation = {
    editReport: {
        id: string;
        name: string;
        date: any;
        bodymaps: ({
            id: string;
            label: string;
            details: string;
        })[];
        user: {
            id: string;
            name: string | null;
        };
    };
};
export type EditReportMutationVariables = {
    id: string;
    name: string;
    date: any;
};
