/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type EditBodyMapMutation = {
    editBodyMap: {
        id: string;
        label: string;
        details: string;
    };
};
export type EditBodyMapMutationVariables = {
    id: string;
    label: string;
    details: string;
};
