/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type ReportQuery = {
    report: ({
        id: string;
        name: string;
        date: any;
        bodymaps: ({
            id: string;
            label: string;
            details: string;
        })[];
        user: {
            id: string;
            name: string | null;
        };
    }) | null;
};
export type ReportQueryVariables = {
    id: string;
};
