/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type DeleteMutation = {
    deleteReport: {
        id: string;
        name: string;
        date: any;
        user: {
            id: string;
            name: string | null;
        };
    };
};
export type DeleteMutationVariables = {
    id: string;
};
